import { graphikFont } from "@/assets/fonts";
import type { Metadata } from "next";
import "./globals.css";
import { Locale, languages } from "@/lib/i18n";
import { LocomotiveScroller } from "@/app/[lang]/components/LocomotiveScroller";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={graphikFont.className}>
        <LocomotiveScroller />
        {children}
      </body>
    </html>
  );
}
